# Generated by Django 4.2.1 on 2023-05-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sse_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.CharField(default='Hello World!', max_length=200),
        ),
    ]
