# Generated by Django 4.2.1 on 2023-05-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sse_app', '0002_alter_notification_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
