# Generated by Django 4.2.1 on 2023-05-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panic',
            name='comment',
            field=models.CharField(default='Testing', max_length=100),
        ),
    ]
