# Generated by Django 4.2.1 on 2023-05-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panic', '0002_panic_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panic',
            name='comment',
        ),
    ]
