# Generated by Django 4.2.1 on 2023-05-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('car_plate', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit_at', models.DateField(verbose_name='Visit at')),
                ('hashed', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
